<?php

// Lykos Reviews Module
// Adapted from Xoopsfaq by Samuel Wright (http://www.lykoszine.co.uk)
// See readme for more info

// ------------------------------------------------------------------------- //
//                XOOPS - PHP Content Management System                      //
//                       <https://www.xoops.org>                             //
// ------------------------------------------------------------------------- //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
// ------------------------------------------------------------------------- //

$modversion['name'] = _MI_LYKOS_REVIEWS_NAME;
$modversion['version'] = 1.00;
$modversion['description'] = _MI_LYKOS_REVIEWS_DESC;
$modversion['credits'] = 'Lykos Zine';
$modversion['author'] = 'Samuel Wright ';
$modversion['help'] = 'lykos_reviews.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/lykoszine.gif';
$modversion['dirname'] = 'lykos_reviews';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'lykos_reviews_contents';
$modversion['tables'][1] = 'lykos_reviews_categories';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Main contents
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_LYKOS_REVIEWS_SMNAME1;
$modversion['sub'][1]['url'] = 'submit.php';

// Blocks
$modversion['blocks'][1]['file'] = 'b_lykos_reviews_latest.php';
$modversion['blocks'][1]['name'] = _MI_B_LATEST;
$modversion['blocks'][1]['description'] = 'Shows latest reviews';
$modversion['blocks'][1]['show_func'] = 'b_lykos_reviews_latest_show';

$modversion['blocks'][2]['file'] = 'b_lykos_reviews_to_add.php';
$modversion['blocks'][2]['name'] = _MI_B_SUBMIT;
$modversion['blocks'][2]['description'] = 'Shows submitted or hidded reviews';
$modversion['blocks'][2]['show_func'] = 'b_lykos_reviews_to_add_show';

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'lykos_reviews_search';
